
services:
  db:
    image: postgres:13
    container_name: agriva_postgres
    environment:
      POSTGRES_USER: agriva_user
      POSTGRES_PASSWORD: agriva_pass
      POSTGRES_DB: agriva_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - agriva_network
  backend:
    build: ./backend
    container_name: agriva_backend
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://agriva_user:agriva_pass@db:5432/agriva_db
    networks:
      - agriva_network

volumes:
  pg_data:

networks:
  agriva_network:
    external: true