
services:
  db:
    image: postgres:13
    container_name: agriva_postgres
    environment:
      POSTGRES_USER: agriva_user
      POSTGRES_PASSWORD: agriva_pass
      POSTGRES_DB: agriva_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - agriva_network
  backend:
    build: ./backend
    container_name: agriva_backend
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://agriva_user:agriva_pass@db:5432/agriva_db
    volumes:
      - ./01_dapur_jupyter/data:/app/raw_data:ro
      - ./01_dapur_jupyter/models:/app/models_output:ro
      - ./backend:/app
    networks:
      - agriva_network
  frontend:
    image: nginx:alpine
    container_name: agriva_frontend
    ports:
      - "5174:80"   # expose on localhost:5174
    volumes:
      - ./frontend:/usr/share/nginx/html:ro   # serve static files
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - agriva_network

volumes:
  pg_data:

networks:
  agriva_network: